version: '3.8'

services:
  frontend: 
    image: yaoktut/infra_frontend:latest
    volumes: 
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  postgres:
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - foodgram_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: yaoktut/infra_backend:latest
    restart: always
    volumes:
      - static_value:/app/backend-static/
      - media_value:/app/backend-media/ 
    depends_on:
      - postgres
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"  # Добавлен порт 443 для HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend-static/
      - media_value:/var/html/backend-media/
      - certbot_data:/etc/letsencrypt  # Добавлен том для хранения сертификатов
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_data:/etc/letsencrypt  # Подключение тома с сертификатами Certbot
      - ./certbot/conf:/etc/letsencrypt  # Монтирование конфигурационных файлов Certbot
      - ./certbot/www:/var/www/certbot  # Монтирование каталога веб-сервера для проверки домена
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d your-domain.com  # Замените на свои реальные данные
    depends_on:
      - nginx
    entrypoint: ""  # Отключение стандартного входного точка Certbot, чтобы он не пытался перезапустить Nginx

volumes:
  static_value:
  media_value:
  foodgram_data:
  certbot_data:
